//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanCloud.LeanMeaasge.Demo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeanCloud.LeanMeaasge.Demo.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string ab_logout {
            get {
                return ResourceManager.GetString("ab_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        public static string ab_register {
            get {
                return ResourceManager.GetString("ab_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  发送.
        /// </summary>
        public static string ab_sendVideo {
            get {
                return ResourceManager.GetString("ab_sendVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeanMessage Demo.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登陆.
        /// </summary>
        public static string btn_login {
            get {
                return ResourceManager.GetString("btn_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送.
        /// </summary>
        public static string btn_send {
            get {
                return ResourceManager.GetString("btn_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开聊.
        /// </summary>
        public static string btn_stepin {
            get {
                return ResourceManager.GetString("btn_stepin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入文字.
        /// </summary>
        public static string hint_inputMessage {
            get {
                return ResourceManager.GetString("hint_inputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入密码.
        /// </summary>
        public static string hint_password {
            get {
                return ResourceManager.GetString("hint_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请再次输入密码.
        /// </summary>
        public static string hint_reinputPassword {
            get {
                return ResourceManager.GetString("hint_reinputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入用户名.
        /// </summary>
        public static string hint_username {
            get {
                return ResourceManager.GetString("hint_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 与 {0} 的对话.
        /// </summary>
        public static string in18_ConversationTitle {
            get {
                return ResourceManager.GetString("in18_ConversationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已选.
        /// </summary>
        public static string lt_selected {
            get {
                return ResourceManager.GetString("lt_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系人.
        /// </summary>
        public static string pt_contacts {
            get {
                return ResourceManager.GetString("pt_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发现.
        /// </summary>
        public static string pt_find {
            get {
                return ResourceManager.GetString("pt_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎.
        /// </summary>
        public static string pt_Login {
            get {
                return ResourceManager.GetString("pt_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我.
        /// </summary>
        public static string pt_me {
            get {
                return ResourceManager.GetString("pt_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会话.
        /// </summary>
        public static string pt_session {
            get {
                return ResourceManager.GetString("pt_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        public static string pt_signup {
            get {
                return ResourceManager.GetString("pt_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string tp_pwd {
            get {
                return ResourceManager.GetString("tp_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        public static string tp_username {
            get {
                return ResourceManager.GetString("tp_username", resourceCulture);
            }
        }
    }
}
